version: '3'
services:
  chat-service:
    # restart: always
    build:
      context: ./
      args:
        SOCKET_PORT: ${SOCKET_PORT}
    volumes:
      - .:/go/src/github.com/Deewai/chat-service
    container_name: chat-service
    ports:
      - "${SOCKET_PORT}:${SOCKET_PORT}"
    tty: true
    # environment:
    #   SOCKET_PORT: 8080
    